# Replace with your Discord Application ID
application_id: "1476506786738606110"

# Activity type: 0 = Playing, 1 = Streaming, 2 = Listening, 3 = Watching
type: 3

# Activity Details
name: "i dont need to be seen."
details: "Watching SrvX"
state: "Founder of Srvx"

# Activity Images
largeImageKey: "mascot"
largeImageText: "SrvX"
smallImageKey: "mascot"
smallImageText: "Owner SrvX"

# Activity URL (optional, works only with certain types)
url: "https://guns.lol/srvbhai01"

# Activity Buttons (optional)
buttons:
  - name: "Discord"
    url: "https://guns.lol/srvbhai01"
  - name: "Other info"
    url: "https://guns.lol/srvbhai01"

# Activity Custom status
custom_status: "Watching"
custom_emoji: "🔥"
